### ISSUE TITLE
Direct support for ustrip?

### ISSUE THREAD

**Issue by ChrisRackauckas** [wsphillips/Conductor.jl#1]
Is direct support for ustrip all that's needed for https://github.com/wsphillips/Conductor.jl/blob/089edeb5bea4c38098a5e1e5381edcd33ca033e0/test/hodgkinhuxley.jl#L34 that register to change to IfElse.ifelse and not be needed?

**Comment by wsphillips** [comment]
`ustrip` isn't strictly necessary here. I'm just being somewhat lazy, overtly cautious about unit exponents, and simultaneously showing that I _could_ pass arbitrary functions in. 

Better solution would be either 1) macro that takes any current units and interpolates the converted value as a constant into a returned function. Or 2) read it from a parameter in a `Electrode/Stimulator` wrapper component. Eventually I'll write a fleshed out module for doing current stimulus patterns (pulse trains/wave patterns, etc) like these properly.

**Comment by ChrisRackauckas** [comment]
okay yeah. I think you should try doing the units directly in MTK, though that system is not quite complete. We'll probably need to work together to get the units really to where they need to be 😅

**Comment by wsphillips** [comment]
implementation of units being tracked by #5
