### ISSUE TITLE
Construct groups of (identical) neurons

### ISSUE THREAD

**Issue by Antomek** [wsphillips/Conductor.jl#16]
We should be able to easily take the dynamics of a single neuron, and then construct a whole group of these neurons.

We need to figure out how to address the individual neurons in each group (e.g. through indexing), and introduce some variations within the group when desired.

**Comment by wsphillips** [comment]
- [ ] util to duplicate a neuron, creating a unique name symbol in the process; combination of `deepcopy` , `@set` , `Base.gensym`, ordered container type to hold neurons for indexed access
- [ ] util to mutate model parameters (note: check precedence of default values too)

**Comment by wsphillips** [comment]
WIP at #62

**Comment by wsphillips** [comment]
Closing since #62 is merged. Distribution assignment tracked in a new issue #69
