### ISSUE TITLE
Adding conductance dynamics to ConductanceSystem

### ISSUE THREAD

**Issue by AndreaRamirezH** [wsphillips/Conductor.jl#20]
Hi @wsphillips,

I'm trying to model a neuron with conductances regulated by an integral control rule that uses the calcium concentration, [Ca]. See https://www.cell.com/neuron/pdf/S0896-6273(14)00292-X.pdf 
The new equations that I want to add are eqs (3) in the paper: 
D(g_i) = 1/tau_g * (mRNA_i - g_i) 
D(mRNA_i) = 1/tau_i * (Ca_{target} - [Ca])

I think that ConductanceSystem could contain the ODESystem with the equations for D(g) and D(mRNA) as well as D(gating variables) but I don't know how to implement these changes. What would be the best way to incorporate them into the code ?

Thanks!

**Comment by AndreaRamirezH** [comment]
Hi @wsphillips, sorry it took me so long to reply. 

Thank you for taking a look and directing me to the fix, it works well :)
Thanks @pjh6654 also for posting your answer!

**Comment by wsphillips** [comment]
No problem. I'm glad it was a useful patch. I've been busy the past couple months but I plan to resume active work on this package either this week or next week. Feel free to follow up with more issues as you find them.
